version: "3.9"
services:
  decision-maker-database:
    image: postgres:16
    container_name: decision-maker-database
    restart: always
    environment:
      POSTGRES_DB: decision-maker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Europe/Berlin

  decision-maker:
    build:
      target: Production
    container_name: decision-maker
    restart: always

networks:
  default:
    name: decision-maker-internal

