version: "3.9"
services:
  decision-maker-database:
    env_file:
      - .env.dev
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  decision-maker:
    env_file:
      - .env.dev
    build:
      target: Development
    ports:
      - "3002:3000"
    volumes:
      - ./internal:/app/internal
      - ./public:/app/public
      - ./src:/app/src
      - ./views:/app/views
      - ./.air.toml:/app/.air.toml
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum

  decision-maker-frontend-watcher:
    container_name: decision-maker-frontend-watcher
    restart: always
    build:
      target: Frontend-Development
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./views:/app/views
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./webpack.config.js:/app/webpack.config.js
