version: "3.9"
services:
  decision-maker-database:
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  decision-maker:
    build:
      target: Development
    ports:
      - "3002:3000"
    volumes:
      - ./:/app

  decision-maker-frontend-watcher:
    container_name: decision-maker-frontend-watcher
    restart: always
    build:
      target: Frontend-Development
    volumes:
      - ./:/app
